apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
  # labels:
  #   serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        # Target 10 requests in-flight per pod.
        autoscaling.knative.dev/target: "10"
        # Disable scale to zero with a minScale of 1.
        # autoscaling.knative.dev/minScale: "1"
        # Limit scaling to 50 pods.
        # autoscaling.knative.dev/maxScale: "50"
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-nodejs
          env:
            - name: TARGET
              value: "Node Sample v1"